//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVLingtoSQL.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVEntityEntities : DbContext
    {
        public DBCVEntityEntities()
            : base("name=DBCVEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adre> Adres { get; set; }
        public virtual DbSet<Calismalar> Calismalars { get; set; }
        public virtual DbSet<Hakkimda> Hakkimdas { get; set; }
        public virtual DbSet<Ilestisim> Ilestisims { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Yetenekler> Yeteneklers { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
